### ISSUE TITLE
User-specific Settings / Configuration

### ISSUE THREAD

**Issue by Mischback** [Mischback/colorizer#23]
There are some things, which should be exposed through *user-specific settings*. This is an additional feature beyond the core functions of the application, thus, it is not part of the [v2 milestone](https://github.com/Mischback/colorizer/milestone/1).

This issue tracks the places, where a *user-specific setting* is beneficial / desired.

- [ ] the ``inputDebounceDelay`` of the ``ColorFormInputMethod`` class
- [ ] which method is used to **display** the colors
  - This will be a major effort, possibly worth a dedicated issue!
  - Idea: All elements that are created to display a color have a dedicated class. Somewhere in the beginning of the DOM hierarchy, a class is set, controlling the method and setting the color is then handled in CSS by custom properties.
  - Dummy code:
    ```html
    <html>
      <body class="rgb" style="--colorized-a=255; --colorized-b=128; --colorized-c=64">
        ...
        <SOME GENERIC ELEMENT class="colorized">
    ``` 

    ```css
    .rgb .colorized {
      background-color: rgb(var(--colorized-a) var(--colorized-b) var(--colorized-c));
    }

    .oklch .colorized {
      background-color: oklch(var(--colorized-a) var(--colorized-b) var(--colorized-c));
    }
    ```
- [ ] ``precision``: Several input methods can operate on decimal numbers / floats. Should this be exposed? Should this be a dynamic thing, meaning that the the precision may be adjusted while using the application?
  - [ ] all *rounding operations* should be performed *as late as possible* (when the value is actually displayed!)
  - [ ] see ``roundToPrecision()`` in ``src/script/utility/index.ts``
- [ ] Light mode / dark mode (??)
  - [Great blog post about implementing a dark/light mode](https://www.bennadel.com/blog/4168-i-finally-implemented-dark-mode-using-css-custom-properties-on-this-blog.htm)
