### ISSUE TITLE
Improve Input of Colors

### ISSUE THREAD

**Issue by Mischback** [Mischback/colorizer#8]
As of now, colors have to be added using hex notation in a *text-based* ``input`` field. This works well enough but is not really convenient.

## Requirements

- [x] switch the existing input to ``type="color"``
  - [x] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color
  - [x] https://www.the-art-of-web.com/javascript/html5-color-input/
  - [x] might require minor changes in ``ColorizerInterface`` and/or in ``ColorizerEngine``, because that input field includes the leading ``#`` character.
- [x] add means to use RGB (based on three input fields for R, G, B with ranges between 0..255)
  - [x] ~~This might be implemented in *frontend-only*, meaning that the actual interface to ``ColorizerEngine`` remains the hex notation (see above, especially the [this resource](https://www.the-art-of-web.com/javascript/html5-color-input/))~~ **Switched** to ``0..255`` internally!
- [x] add means to use HSL
- [x] add means to use HWB
- ~~add means to use [Oklab](https://www.w3.org/TR/css-color-4/#specifying-oklab-oklch)~~ **Not for now! ``Oklch`` seems more intuitive!**
- [x] add means to use [Oklch](https://www.w3.org/TR/css-color-4/#specifying-oklab-oklch)

## Resources
  - https://www.w3.org/TR/css-color-4/ This is the most recent version of the CSS color module. Beside the formal description it includes example implementation of conversion functions
  - https://gist.github.com/mjackson/5311256 Different conversion functions between different color models (e.g. RGB to HSL, HSL to RGB)
  - The conversion from [Oklab/Oklch](https://www.w3.org/TR/css-color-4/#specifying-oklab-oklch) to ``sRGB`` (which is predominant for usual computer screens) is described [here](https://www.w3.org/TR/css-color-4/#oklab-lab-to-predefined), including [sample implementation in JS](https://www.w3.org/TR/css-color-4/#color-conversion-code)

**Comment by Mischback** [comment]
## Getting started

```HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Colorizer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--<link rel="stylesheet" href="assets/style.css">-->
    <!--<script src="assets/colorizer.js" defer></script>-->
    <style>
      #ctrl {
        margin: 10px;
        padding: 0.5em;
        border: 3px solid #333;
      }
      #ctrl h3 {
        margin: 0 0 1em 0;
      }
    </style>
  </head>

  <body>
    <header>
      <h1>Colorizer</h1>
      <p>A tool to build color palettes while considering contrast values.</p>
    </header>
    <section id="ctrl">
      <section>
        <h3>Add new Color</h3>
        <div>
          <form id="color-add">
            <fieldset>
              <legend>Hex / Color Picker input</legend>
              <ul>
                <li>
                  <label for="new-color">New Color</label>
                  <input id="new-color" type="color" required>
                </li>
                <li>
                  <label for="new-color-hex">Hex Input</label>
                  <input id="new-color-hex" type="text">
                </li>
              </ul>
            </fieldset>
            <fieldset>
              <legend>RGB input</legend>
              <ul>
                <li>
                  <label for="new-color-rgb-r">R</label>
                  <input id="new-color-rgb-r" type="number" min="0" max="255">
                </li>
                <li>
                  <label for="new-color-rgb-g">G</label>
                  <input id="new-color-rgb-g" type="number" min="0" max="255">
                </li>
                <li>
                  <label for="new-color-rgb-b">B</label>
                  <input id="new-color-rgb-b" type="number" min="0" max="255">
                </li>
              </ul>
            </fieldset>
            <fieldset>
              <legend>HSL input</legend>
              <ul>
                <li>
                  <label for="new-color-hsl-h">H</label>
                  <input id="new-color-hls-h" type="number" min="0" max="255">
                </li>
                <li>
                  <label for="new-color-hsl-s">S</label>
                  <input id="new-color-hsl-s" type="number" min="0" max="255">
                </li>
                <li>
                  <label for="new-color-hsl-l">L</label>
                  <input id="new-color-hsl-l" type="number" min="0" max="255">
                </li>
              </ul>
            </fieldset>
            <fieldset>
              <legend>HSV input</legend>
              <ul>
                <li>
                  <label for="new-color-hsv-h">H</label>
                  <input id="new-color-hlv-h" type="number" min="0" max="255">
                </li>
                <li>
                  <label for="new-color-hsv-s">S</label>
                  <input id="new-color-hsv-s" type="number" min="0" max="255">
                </li>
                <li>
                  <label for="new-color-hsv-v">V</label>
                  <input id="new-color-hsv-v" type="number" min="0" max="255">
                </li>
              </ul>
            </fieldset>
          </form>
        </div>
        <div>
          Live Preview with utility informations.
        </div>
      </section>
    </section>

    <script type="text/javascript">
      let addColor_inputColorInput;
      let addColor_inputRgbRInput;

      function addColor_applyColorInput(e) {
        console.debug("applyColorInput()");

        // FIXME: Calculate the values for RGB/HSL/HSV and apply them!
        addColor_inputRgbRInput.value = 5;
      }

      function addColor_applyRgbInput(e) {
        console.debug("applyRgbInput()");

        addColor_inputColorInput.value = "#ff0000";
      }

      class addColorForm {
        // Declare private attributes
        #currentColor;
        #currentColorObservers;

        constructor(
          colorInput,
          colorInputHex,
          rgbInputR, rgbInputG, rgbInputB
        ) {
          try {
            this.colorInput = document.querySelector(colorInput);
            if (this.colorInput === null)
              throw new Error(`Missing required element with id '${colorInput}'`);

            this.colorInputHex = document.querySelector(colorInputHex);
            if (this.colorInputHex === null)
              throw new Error(`Missing required element with id '${colorInputHex}'`);

            this.rgbInputR = document.querySelector(rgbInputR);
            if (this.rgbInputR === null)
              throw new Error(`Missing required element with id '${rgbInputR}'`);
            this.rgbInputR.addEventListener("input", this.#setColorFromRgb.bind(this));

            this.rgbInputG = document.querySelector(rgbInputG);
            if (this.rgbInputG === null)
              throw new Error(`Missing required element with id '${rgbInputG}'`);
            this.rgbInputG.addEventListener("input", this.#setColorFromRgb.bind(this));

            this.rgbInputB = document.querySelector(rgbInputB);
            if (this.rgbInputB === null)
              throw new Error(`Missing required element with id '${rgbInputB}'`);
            this.rgbInputB.addEventListener("input", this.#setColorFromRgb.bind(this));
          } catch (e) {
            console.error(e.name, e.message);
          }

          // Define / initialize private attributes
          this.#currentColorObservers = [];

          // TODO: This is only for development!
          this.observeCurrentColorChange((c) => {
            console.info(`[DEBUG] new color: ${c.r}, ${c.g}, ${c.b}!`);
          });

          this.observeCurrentColorChange(this.#applyToColorInput.bind(this));
          this.observeCurrentColorChange(this.#applyToHexInput.bind(this));
          this.observeCurrentColorChange(this.#applyToRgbInput.bind(this));

          this.#setCurrentColor({r: 255, g: 128, b: 32});
        }

        observeCurrentColorChange(cb) {
          this.#currentColorObservers.push(cb);
        }

        #setCurrentColor({r = 0, g = 0, b = 0} = {}) {
          this.#currentColor = {r: r, g: g, b: b};

          this.#currentColorObservers.forEach((cb) => {
            cb(this.#currentColor);
          });
        }

        #setColorFromRgb(e) {
          console.debug("Set new color from RGB input");
          this.#setCurrentColor({
            r: this.rgbInputR.value,
            g: this.rgbInputG.value,
            b: this.rgbInputB.value,
          });
        }

        #applyToColorInput(newColor) {
          console.debug("Set new color for this.colorInput!");
          let hexColor = "#" + (1 << 24 | newColor.r << 16 | newColor.g << 8 | newColor.b).toString(16).slice(1);
          this.colorInput.value = hexColor;
        }

        #applyToHexInput(newColor) {
          console.debug("Set new color for this.colorInputHex!");
          let hexColor = "#" + (1 << 24 | newColor.r << 16 | newColor.g << 8 | newColor.b).toString(16).slice(1);
          this.colorInputHex.value = hexColor;
        }

        #applyToRgbInput(newColor) {
          console.debug("Set new color for this.rgbInput[RGB]!");
          this.rgbInputR.value = newColor.r;
          this.rgbInputG.value = newColor.g;
          this.rgbInputB.value = newColor.b;
        }
      }

      document.addEventListener("DOMContentLoaded", () => {
        console.info("DOM ready, doing stuff!");

        let formEngineAddColor = new addColorForm(
          "#new-color",
          "#new-color-hex",
          "#new-color-rgb-r",
          "#new-color-rgb-g",
          "#new-color-rgb-b",
        );
      });
    </script>
  </body>
</html>
```

**Comment by Mischback** [comment]
## Dry Coding

```HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Colorizer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="assets/style.css">
    <script src="assets/colorizer.js" defer></script>
  </head>

  <body>
    <header>
      <h1>Colorizer</h1>
      <p>A tool to build color palettes while considering contrast values.</p>
    </header>

    <section id="ctrl">
      <button id="ctrl-toggle">&gt;</button>

      <section id="color-add">
        <h3>Add new Color</h3>

          <form id="color-add-form">
            <fieldset class="color-input">
              <legend>Hex / Color Picker input</legend>
              <div>
                <label for="new-color-pick">New Color:</label>
                <div id="new-color-pick-wrapper"><input id="new-color-pick" type="color"></div>
              </div>
              <div>
                <label for="new-color-hex">Hex Input:</label>
                <input id="new-color-hex" type="text">
              </div>
            </fieldset>
            <fieldset>
              <legend>RGB input</legend>
              <div class="component-input">
                <label for="new-color-rgb-r">R:</label>
                <input id="new-color-rgb-r" type="number" min="0" max="255">
              </div>
              <div class="component-input">
                <label for="new-color-rgb-g">G:</label>
                <input id="new-color-rgb-g" type="number" min="0" max="255">
              </div>
              <div class="component-input">
                <label for="new-color-rgb-b">B:</label>
                <input id="new-color-rgb-b" type="number" min="0" max="255">
              </div>
            </fieldset>
            <fieldset>
              <legend>HSL input</legend>
              <div class="component-input">
                <label for="new-color-hsl-h">H:</label>
                <input id="new-color-hsl-h" type="number" min="0" max="360">
              </div>
              <div class="component-input">
                <label for="new-color-hsl-s">S:</label>
                <input id="new-color-hsl-s" type="number" min="0" max="100">
              </div>
              <div class="component-input">
                <label for="new-color-hsl-l">L:</label>
                <input id="new-color-hsl-l" type="number" min="0" max="100">
              </div>
            </fieldset>
            <button type="submit">Add</button>
          </form>

      </section>

      <section id="color-palette">
          <ul></ul>
      </section>
    </section>

    <section id="contrast-grid"></section>
  </body>
</html>
```

```CSS
* {
  margin: 0;
  padding: 0;
}

body {
  font-family: Verdana, sans-serif;
  background-color: #868686;
  color: #000;
  box-sizing: border-box;
}

#contrast-grid {
  display: inline-block;
  margin: 1em 1em 1em 3rem;
  padding: 1em;
}

.grid-element {
  padding: 0.5em;
  font-size: 0.7em;
  display: inline-block;
  width: 6em;
  height: 6em;
  text-align: right;
  border: 1px solid #000;
}

.grid-element .w3cat {
  font-weight: bold;
  font-size: 2em;
}

.grid-element .color-value {
  font-weight: bold;
}

header {
  margin: 1px 0 1rem 0;
  padding: 0.5rem 1rem 1rem 1rem;
  position: relative;
  text-align: right;
  background: linear-gradient(to top, #868686, rgba(0, 0, 0, 60%) 5px, #999 7px);
}

#ctrl {
  position: absolute;
  top: 1rem;
  left: -50vw;
  width: 50vw;
  height: calc(100vh - 5rem);
  background-color: #444;
  color: #fefefe;
  padding: 1em;
  box-shadow: inset 0 0 3px 2px rgba(0, 0, 0, 60%);
  border-top-right-radius: 1.5rem;
  border-bottom-right-radius: 0.5rem;
}

/* TEMPORARILY REMOVED
#color-add {
  margin: 0.5em 0 1em 0;
}

#color-add form label {
  display: block;
  font-size: 0.7em;
}

#color-add form input {
  border: none;
  border-bottom: 1px solid #fefefe;
  background-color: #868686;
  padding: 0.5em 1em;
  font-size: 1.2em;
  border-radius: 5px;
}

#color-add form button {
  font-size: 1.2em;
  padding: 0.5em 1em;
}
*/

#ctrl-toggle {
  position: absolute;
  top: 1.75rem;
  right: -1rem;
  font-size: 1.5rem;
}

button {
  color: #333;
  border: none;
  box-shadow: 0 0 3px 2px rgba(0, 0, 0, 60%);
  background: linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 15% 40%, #d0d0d0 50% 90%, #666 95%);
  border-radius: 5px;
  font-weight: bold;
  padding: 0.25em 0.5em;
}
button:hover {
  background: linear-gradient(to bottom, #eedd99 5%, #ffcc00 15% 40%, #eeaa00 50% 90%, #666 95%);
}

#color-palette ul {
  margin: 3em 0;
  padding: 0;
  list-style: none;
}
#color-palette ul li {
  display: inline-block;
  background-color: #f00;
  color: #000;
  padding: 0.25em 0.5em;
  margin: 0.25em 0.5em;
  border-radius: 5px;
  background-color: #888;
}

#color-palette ul li span {
  display: inline-block;
  vertical-align: middle;
  font-family: monospace;
  font-size: 1.1em;
}
#color-palette ul li button {
  vertical-align: middle;
}
#color-palette ul li div {
  display: inline-block;
  vertical-align: middle;
  width: 1.5em;
  height: 1.5em;
  border: 1px solid rgba(0, 0, 0, 60%);
  border-radius: 5px;
  margin: 0 0.5em;
}


#color-add-form {
  display: flex;
}

#color-add-form > fieldset {
  flex: 1 1 auto;
  margin: 1em;
  padding: 0.5em;
}

#color-add-form input {
  font-size: 1.5em;
  margin: 0.25em 0;
  padding: 0.1em 0.25em;
  border: 1px solid #fff;
  background-color: #868686;
}

#color-add-form label {
  display: inline-block;
}

#color-add-form .component-input > label {
  width: 1.5em;
}
#color-add-form .component-input > input {
  width: 3em;
  text-align: right;
}

#color-add-form .color-input label {
  width: 6em;
}
#color-add-form #new-color-hex {
  width: 4em;
  text-align: center;
}

/* based on https://stackoverflow.com/a/65021768 */
#color-add-form #new-color-pick {
  padding: 0;
  width: 150%;
  height: 150%;
  margin: -25%;
  background-color: #f0f;
}
#color-add-form #new-color-pick-wrapper {
  width: 4.5em;
  height: 4.2em;
  display: inline-block;
  border: 1px solid #fff;
  font-size: 1.5em;
  overflow: hidden;
}
```

**Comment by Mischback** [comment]
## BAK

```css
* {
  margin: 0;
  padding: 0;
}

body {
  font-family: Verdana, sans-serif;
  background-color: #868686;
  color: #000;
  box-sizing: border-box;
}

#contrast-grid {
  display: inline-block;
  margin: 1em 1em 1em 3rem;
  padding: 1em;
}

.grid-element {
  padding: 0.5em;
  font-size: 0.7em;
  display: inline-block;
  width: 6em;
  height: 6em;
  text-align: right;
  border: 1px solid #000;
}

.grid-element .w3cat {
  font-weight: bold;
  font-size: 2em;
}

.grid-element .color-value {
  font-weight: bold;
}

header {
  margin: 1px 0 1rem 0;
  padding: 0.5rem 1rem 1rem 1rem;
  position: relative;
  text-align: right;
  background: linear-gradient(to top, #868686, rgba(0, 0, 0, 60%) 5px, #999 7px);
}

#ctrl {
  --primary-bg-color: #444;
  --primary-fg-color: #fefefe;
  --secondary-fg-color: #c2c2c2;

  position: absolute;
  top: 1rem;
  left: -50vw;
  width: 50vw;
  height: calc(100vh - 5rem);
  background-color: var(--primary-bg-color);
  color: var(--primary-fg-color);
  padding: 1em;
  box-shadow: inset 0 0 3px 2px rgba(0, 0, 0, 60%);
  border-top-right-radius: 1.5rem;
  border-bottom-right-radius: 0.5rem;
}

/* TEMPORARILY REMOVED
#color-add {
  margin: 0.5em 0 1em 0;
}

#color-add form label {
  display: block;
  font-size: 0.7em;
}

#color-add form input {
  border: none;
  border-bottom: 1px solid #fefefe;
  background-color: #868686;
  padding: 0.5em 1em;
  font-size: 1.2em;
  border-radius: 5px;
}

#color-add form button {
  font-size: 1.2em;
  padding: 0.5em 1em;
}
*/

#ctrl-toggle {
  position: absolute;
  top: 1.75rem;
  right: -1rem;
  font-size: 1.5rem;
}

button {
  color: #333;
  border: none;
  box-shadow: 0 0 3px 2px rgba(0, 0, 0, 60%);
  background: linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 15% 40%, #d0d0d0 50% 90%, #666 95%);
  border-radius: 5px;
  font-weight: bold;
  padding: 0.25em 0.5em;
}
button:hover {
  background: linear-gradient(to bottom, #eedd99 5%, #ffcc00 15% 40%, #eeaa00 50% 90%, #666 95%);
}

#color-palette ul {
  margin: 3em 0;
  padding: 0;
  list-style: none;
}
#color-palette ul li {
  display: inline-block;
  background-color: #f00;
  color: #000;
  padding: 0.25em 0.5em;
  margin: 0.25em 0.5em;
  border-radius: 5px;
  background-color: #888;
}

#color-palette ul li span {
  display: inline-block;
  vertical-align: middle;
  font-family: monospace;
  font-size: 1.1em;
}
#color-palette ul li button {
  vertical-align: middle;
}
#color-palette ul li div {
  display: inline-block;
  vertical-align: middle;
  width: 1.5em;
  height: 1.5em;
  border: 1px solid rgba(0, 0, 0, 60%);
  border-radius: 5px;
  margin: 0 0.5em;
}


/* REFACTOR THE COLOR FORM */

#color-add-form {
  display: flex;
  flex-flow: row wrap;
  gap: 1em;
}

#color-add-form > fieldset {
  flex: 1 1 auto;
  padding: 0.5em;
  color: var(--secondary-fg-color);
}
#color-add-form > button {
  flex: 0 0 100%;
  font-size: 1.5em;
  font-weight: normal;
}

#color-add-form input {
  font-size: 1.5em;
  margin: 0.25em 0;
  padding: 0.1em 0.25em;
  border: none;
  border-bottom: 1px solid var(--secondary-fg-color);
  background-color: var(--primary-bg-color);
  color: var(--secondary-fg-color);
}
#color-add-form div:hover input {
  color: var(--primary-fg-color);
}
#color-add-form div:hover label {
  color: var(--primary-fg-color);
}
#color-add-form div:focus-within input {
  outline: none;
  border: none;
  background-color: #00ff00;
  color: #000;
  border-bottom: 1px solid #f0f000;
}
#color-add-form div:focus-within label {
  color: #f00;
}

#color-add-form label {
  display: inline-block;
}

#color-add-form .component-input > label {
  width: 1.5em;
}
#color-add-form .component-input > input {
  width: 3em;
  text-align: right;
}

#color-add-form .color-input label {
  width: 6em;
}
#color-add-form #new-color-hex {
  width: 4em;
  text-align: center;
}

/* based on https://stackoverflow.com/a/65021768 */
#color-add-form #new-color-pick {
  padding: 0;
  width: 150%;
  height: 150%;
  margin: -25%;
  background-color: #f0f;
}
#color-add-form #new-color-pick-wrapper {
  width: 4.5em;
  height: 4.2em;
  display: inline-block;
  border: 1px solid var(--secondary-fg-color);
  font-size: 1.5em;
  overflow: hidden;
}
```

**Comment by Mischback** [comment]
## partially refactores

only structural aspects for now!

```css
* {
  margin: 0;
  padding: 0;
}

:root {
  --color-not-defined-one: #f0f;
  --color-not-defined-two: #0f0;

  /* Actual settings */
  font-family: Verdana, sans-serif;  /* TODO: Provide a full system font stack */
  font-size: 16px;
  color: var(--color-not-defined-one);
  background-color: var(--color-not-defined-two);
}

/* General Structure */

header {
  margin: 1px 0 1rem 0;
  padding: 0.5em 1em 1em 1em;
  text-align: right;
}

#ctrl {
  --dim-ctrl-panel-width: 75vw;

  position: absolute;
  top: 1rem;
  /* FIXME:
     Handle the positioning of the collapsed and expanded control menu in
     dedicated CSS classes and modify the JS code to remove/add the
     corresponding CSS class, depending on an internal state
     Include some additional room to hide the inset shadow on the left side of
     the panel.
  */
  left: calc(-1 * var(--dim-ctrl-panel-width));
  width: var(--dim-ctrl-panel-width);
  height: calc(100vh - 5rem);
  padding: 1em;
  border-top-right-radius: 1.5rem;
  border-bottom-right-radius: 0.5rem;
  /* FIXME: Adjust colors! */
  box-shadow: inset 0 0 3px 2px rgba(255 255 255 / 90%),
    inset 0 0 4px 2px rgba(0 0 0 / 90);
}

#ctrl-toggle {
  position: absolute;
  top: 1.75rem;
  right: -1rem;
  font-size: 1.5rem;
}

#color-add-form {
  display: flex;
  flex-flow: row wrap;
  gap: 1em;
}

#color-add-form > fieldset {
  flex: 1 1 auto;
  padding: 0.5em;
}


/* Contrast Grid
 *
 * This is the general layout of the contrast grid.
 *
 * Please note, that some styling-related attributes, like the
 * ``.grid-element``'s foreground and background color are set dynamically
 * using the ``style`` attribute from within the ``ColorizerEngine`` JS code.
 */

#contrast-grid {
  display: inline-block;
  margin: 1em 1em 1em 3rem;
  padding: 1em;
}

.grid-element {
  padding: 0.5em;
  font-size: 0.7em;
  display: inline-block;
  width: 6em;
  height: 6em;
  text-align: right;
  /* FIXME: Check / adjust color! */
  border: 1px solid #000;
}

.grid-element .w3cat {
  font-weight: bold;
  font-size: 2em;
}

.grid-element .color-value {
  font-weight: bold;
}
```
